### ISSUE TITLE
Cannot get TTS to work

### ISSUE THREAD

**Issue by cmfrazier** [PrayerfulDrop/Hubitat#1]
I'm using Alexa TTS Manager for my Echos. They appear in the NOAA App config and I have them selected, but but I try a test, the logs say `Speech device(s) has not been selected.` 

<img width="1784" alt="Logs" src="https://user-images.githubusercontent.com/20451193/61080591-0818dd00-a3eb-11e9-9157-94f8a01b6be3.png">
<img width="1809" alt="App Setting" src="https://user-images.githubusercontent.com/20451193/61080592-0818dd00-a3eb-11e9-8639-593917abaa3f.png">

**Comment by PrayerfulDrop** [comment]
I would recommend either selecting them as music devices OR switch over the Echo Speaks vs the Alexa TTS manager.

**Comment by cmfrazier** [comment]
They are not shown as music speakers. I don't have any issues with any other TTS apps. It's odd they show up, but the logs say none selected.

**Comment by PrayerfulDrop** [comment]
I am probably not sending the correct command in the speech speakers. I personally use Echo Speaks. If you choose Echo Speaks for the device list do they appear there?  If so try that.  

Most users have moved to Echo Speaks which solves the cookie expiration issue.
